version: '3.5'

networks:
  mlc_net:
    driver: bridge
    name: mlc_net

services:
  api:
    build: . 
    ports:
      - 8000:8000
    environment:
      - CURRENCY_SLUG=${CURRENCY_SLUG}
      - CURRENCY_SYMBOL=${CURRENCY_SYMBOL}
      - ENV=${ENV}
      - SESSION_TIMEOUT=${SESSION_TIMEOUT}
      - MIN_LENGTH_PWD=${MIN_LENGTH_PWD}
      - MAX_LENGTH_PWD=${MAX_LENGTH_PWD} 
      - DJANGO_DEBUG=${DJANGO_DEBUG} 
      - API_PUBLIC_URL=http://localhost:8000
      - DOLIBARR_PUBLIC_URL=http://localhost:8080
      - BDC_PUBLIC_URL=http://localhost:8001
      - GI_PUBLIC_URL=http://localhost:8002
      - CEL_PUBLIC_URL=http://front:8000
      - EMAIL_NOTIFICATION_GESTION=${EMAIL_NOTIFICATION_GESTION}
      - RAVEN_CONFIG_DSN=http://46498c24303d4b27828e5e47ce927818:6177efcf6d1d47508f1c22332c8dddaf@sentry:9000/2
    depends_on:
      - cyclos-app
    stdin_open: true
    tty: true
    networks:
      - mlc_net

  # selenium:
  #   image: selenium/standalone-firefox-debug
  #   container_name: eusko_selenium
  #   depends_on:
  #     - api
  #   ports:
  #     - 4444:4444
  #     - 5900:5900
  #   networks:
  #     - eusko_net

  #  dolibarr-app:
  #    image: euskalmoneta/dolibarr:custom
  #    ports:
  #      - 8080:80
  #    volumes:
  #      - ./data/documents:/var/www/documents
  #      - ./etc/dolibarr/conf.php:/var/www/html/conf/conf.php
  #      - ./etc/dolibarr/date-timezone.ini:/usr/local/etc/php/conf.d/date-timezone.ini
  #    depends_on:
  #      - dolibarr-db
  #      - cyclos-app
  #    networks:
  #      - eusko_net
  #
  #  dolibarr-db:
  #    image: mariadb:10.1
  #    volumes:
  #      - ./etc/dolibarr/dump:/docker-entrypoint-initdb.d
  #      - ./data/mariadb:/var/lib/mysql
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=pass
  #      - MYSQL_DATABASE=pass
  #      - MYSQL_USER=pass
  #      - MYSQL_PASSWORD=pass
  #    networks:
  #      - eusko_net
  #
 
  cyclos-app:
    image: cyclos/cyclos:4.11.2
    environment:
    - DB_HOST=cyclos-db
    - DB_NAME=${POSTGRES_DB}
    - DB_USER=${POSTGRES_USER}
    - DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - '${CYCLOS_PORT}:8080'
    networks:
      - mlc_net

  cyclos-db:
    image: cyclos/db
    environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - mlc_net


  # sentry-redis:
  #   image: redis
  #   networks:
  #     - eusko_net

  # sentry-postgres:
  #   image: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=sentry
  #     - POSTGRES_USER=sentry
  #   volumes:
  #     - ./data/postgresql:/var/lib/postgresql/data
  #   networks:
  #     - eusko_net

  # sentry:
  #   image: sentry
  #   environment:
  #     - SENTRY_SECRET_KEY="x4^nd^1k9k8=8#sa1$gu72p-g15a(ft8(d@jy@^d$ec!oe!"
  #     - SENTRY_POSTGRES_HOST=sentry-postgres
  #     - SENTRY_DB_USER=sentry
  #     - SENTRY_DB_PASSWORD=sentry
  #     - SENTRY_REDIS_HOST=sentry-redis
  #   ports:
  #     - 9000:9000
  #   links:
  #     - sentry-redis:redis
  #     - sentry-postgres:postgres
  #   networks:
  #     - eusko_net

  # sentry-cron:
  #   image: sentry
  #   environment:
  #     - SENTRY_SECRET_KEY="x4^nd^1k9k8=8#sa1$gu72p-g15a(ft8(d@jy@^d$ec!oe!"
  #     - SENTRY_POSTGRES_HOST=sentry-postgres
  #     - SENTRY_DB_USER=sentry
  #     - SENTRY_DB_PASSWORD=sentry
  #     - SENTRY_REDIS_HOST=sentry-redis
  #   links:
  #     - sentry-redis:redis
  #     - sentry-postgres:postgres
  #   networks:
  #     - eusko_net
  #   command: sentry run cron

  # sentry-worker:
  #   image: sentry
  #   environment:
  #     - SENTRY_SECRET_KEY="x4^nd^1k9k8=8#sa1$gu72p-g15a(ft8(d@jy@^d$ec!oe!"
  #     - SENTRY_POSTGRES_HOST=sentry-postgres
  #     - SENTRY_DB_USER=sentry
  #     - SENTRY_DB_PASSWORD=sentry
  #     - SENTRY_REDIS_HOST=sentry-redis
  #   links:
  #     - sentry-redis:redis
  #     - sentry-postgres:postgres
  #   networks:
  #     - eusko_net
  #   command: sentry run worker


