version: '3.5'

services:
  api:
    volumes:
      - ./src/api:/usr/src/app
      - ./etc/cyclos:/cyclos
      - ./etc/dolibarr:/dolibarr

  cyclos-db:
    volumes:
        - ./data/cyclos/postgresql:/var/lib/postgresql/data
        - ./etc/cyclos/dump/cyclos.sql:/cyclos.sql

      
